---

#- name: Add tower credential
#  tower_credential:
#    name: "{{ organization_name }}_ssh_Credential"
#    kind: "ssh"
#    #ssh_key_data: "{{ SSH_Credential_key_location }}"
#    description: This is a ssh credential for {{ organization_name }} used for auth to Linux #servers
#    project: "Foo"
#    state: present
#    tower_verify_ssl: "{{ verify_ssl }}"


#- name: Add tower credential
#  tower_credential:
#    name: "foo_git_credential"
#    organization: "{{ organization_name }}"
#    kind: "scm"
#    description: This is a git credential for project Foo
#    user: extktd
#    state: present
#    tower_verify_ssl: "{{ verify_ssl }}"
