---

- name: Add credentials
  command: tower-cli credential create --name="{{ item.name }}" --team="{{ tower_team.name }}" --credential-type="{{ item.credential_type }}" --inputs=" {{ {'username':"}}{{ item.username }}{{",'password':"}}{{ item.password }}{{"} }}"
  with_items:
    - "{{ tower_team.tower_credentials }}"
  register: result
  changed_when: result.stdout | search("true")

