---

- name: Create tower organization
  tower_organization:
    name: "{{ organization }}"
    description: "{{ organization_description }}"
    state: "{{ organization_state }}"
    tower_verify_ssl: "{{ verify_ssl }}"
