---

- name: Add tower project
  tower_project:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization }}"
    scm_credential: "{{ item.scm_credential }}"
    scm_type: "{{ item.scm_type }}"
    scm_branch: "{{ item.scm_branch }}"
    scm_update_on_launch: "{{ item.scm_update_on_launch }}"
    scm_url: "{{ item.scm_url }}"
    state: "{{ item.state }}"
    tower_verify_ssl: "{{ verify_ssl }}"
  with_items: "{{ tower_team.tower_projects }}"
