---

#
# As the user should be present via a LDAP login we only need to associate the user with the
# correct team
- name: Add tower user
  tower_user:
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    email: "{{ item.email }}"
    first_name: "{{ item.first_name }}"
    last_name: "{{ item.last_name }}"
    superuser: "{{ item.superuser }}"
    state: "{{ item.state }}"
    tower_verify_ssl: "{{ verify_ssl }}"
  with_items: "{{ tower_team.tower_users }}"


- name: Associate users whith team
  shell: tower-cli user list --username  {{ item.username }}
  with_items: "{{ tower_team.tower_users }}"
  register: list_user_result
  failed_when: list_user_result.stdout | match("No records found.")
  changed_when: false


#
# As this method is missing in tower module we use tower-cli to associate user with team.
#
- name: Associate users whith team.
  command: tower-cli team associate --team "{{ tower_team.name }}" --user "{{ item.username }}"
  with_items: 
    - "{{ tower_team.tower_users }}"
  register: result
  changed_when: result.stdout | search("true")
